name: Continuos Training
on:
  push:
    branches: 
    - workflow_continuos_training
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this?
        required: false
        default: running CT
jobs:
  continuos-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl.dvc -r model-track
          dvc unprotect model/model.pkl
          dvc repro -f
          echo "Training Complete"
          dvc add model/model.pkl 
          dvc push model/model.pkl.dvc -r model-track
          cat report.txt >> report.md
          cml-publish prediction_behavior.png --md >> report.md
          cml-send-comment report.md
      # - name: Commit .dvc file changes
      #   run: |
      #     git config --local user.email "jcasjar@gmail.com"
      #     git config --local user.name "github-actions[bot-MM]"
      #     git add model/model.pkl.dvc
      #     git commit -m 'Updating model serialization'
      # - uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}